name: unilink2023
description: Aplicacao da faculdade desenvolvida no ambito da cadeira ADC
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter
    
  http: ^0.13.5
  intl: any
  introduction_screen: ^3.1.8
  lottie: ^2.3.2
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  cupertino_icons: ^1.0.0
  flutter_svg: ^2.0.5
  google_fonts: ^4.0.4 # to import google fonts and text theme
  image_picker: ^0.8.7+2
  firebase_storage: ^11.2.1
  cloud_firestore: ^4.5.0
  firebase_core: ^2.10.0
  universal_io: ^2.2.0
  file_picker: ^5.2.10
  sqflite: ^2.2.8+2
  path: ^1.8.2
  universal_html: ^2.2.1
  firebase_database: ^10.2.1
  video_player: ^2.2.10
  photo_view: ^0.14.0
  html: any
  url_launcher: ^6.0.15
  firebase_auth: ^4.6.2
  firebase_messaging: "^14.6.3"
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  flutter_local_notifications: ^9.4.0
  flutter_launcher_icons: "^0.9.2"
  android_intent: ^2.0.2
  package_info_plus: ^4.0.2
  alphabet_list_view: ^0.1.8
  searchfield: ^0.8.3
  font_awesome_flutter: ^9.2.0
  json_annotation: ^4.1.0
  table_calendar: ^3.0.0
  google_maps_flutter: any
  path_provider: ^2.0.15
  camera: ^0.10.5+2
  location: ^4.4.0
  flutter_polyline_points: any
  permission_handler: ^10.3.0
  cached_network_image: ^3.2.0
  google_translator: ^1.0.0
  country_flags: ^2.1.0
  circle_flags: ^0.0.3
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/ICON_UNILINK-03.png"
 
  #adaptive_icon_background: '#6FAF4C'

   

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  generate: true 
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animation/
    - assets/videos/
    - assets/json/
    - assets/json/map/
    - assets/icon/
    #- assets/icon/ICON_UNILINK-03.png
    #- assets/icon/building.png
    #- assets\icon\Parking.png
    #- assets\icon\service.png
    #- assets\icon\gates.png
    #- assets/icon/restaurant.png
    #- assets/icon/restaurant2.png
    #- assets/icon/movingLocation.png
    #- assets/icon/portuguese_flag.png
    #- assets/icon/english_flag.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
 
