runtime: java11
inbound_services:
- warmup
auto_id_policy: default
beta_settings:
  'source_reference': 'https://github.com/FranciscoJRFreitas/ADC-UNILINK.git#e9c3fbe86eb6ea799b7a8fe722848b7b40b0ab39'
handlers:
- url: (/registSU/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/registSU/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
- url: (/registSU/.*\.cur)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*/)
  static_files: __static__\1index.html
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
- url: (/registSU/.*\.ico)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.cur)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/registSU/.*\.ttf)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.ico)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/registSU/.*\.wav)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.ttf)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/registSU/.*\.mp3)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.wav)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/registSU/.*\.png)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.mp3)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/registSU/.*\.gif)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.png)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/registSU/.*\.jpg)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.gif)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/registSU/.*\.js)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.jpg)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/registSU/.*\.css)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.js)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/registSU/.*\.html)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: admin
  secure: optional
  expiration: 1m
- url: (/.*\.css)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: (/.*\.html)
  static_files: __static__\1
  upload: __NOT_USED__
  require_matching_file: True
  login: optional
  secure: optional
  expiration: 1m
- url: /registSU
  script: unused
  login: admin
  secure: optional
- url: /registSU/.*
  script: unused
  login: admin
  secure: optional
- url: /.*
  script: unused
  login: optional
  secure: optional
